[package]
name = "mient"
version = "0.1.0"
authors = ["Cédric Barreteau"]
edition = "2018"

[dependencies]
matrix-sdk = "*"
url = "*"
unicode-width = "*"

tui = "*"
termion = "*"

tokio = "0.2.24"
async-trait = "*"

serde = { version = "*", features = ["derive"] }
serde_json = "*"
